name: Deploy to Minikube (Raspberry Pi)

on:
  workflow_run:
    workflows: ["Run unit tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    env:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_SECRET: $POSTGRES_USER
      TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
      ACCESS_TOKEN_DURATION: $ACCESS_TOKEN_DURATION
      REFRESH_TOKEN_DURATION: $REFRESH_TOKEN_DURATION
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Launch docker-compose
        run: docker compose -f docker-compose.yaml up -d
